name: Deploy to Neocities
on:
  push:
    branches:
      - main
concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Deploy to Neocities
      # You may pin to the exact commit or the version.
      # uses: bcomnes/deploy-to-neocities@8f42b3ee868450c52d65bfb8cc432bc2f30a3f22
      uses: bcomnes/deploy-to-neocities@v1.1.21
      with:
        # Neocities API token for site to deploy to
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        # Local folder to deploy to neocities
        dist_dir: public
        # Delete orphaned files on neocities that don't exist in distDir
        cleanup: false
